# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Allow one concurrent deployment
concurrency:
  group: "testing"
  cancel-in-progress: true

jobs:
  macos-unit:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v4
    - name: Switch Xcode 🔄
      run: sudo xcode-select --switch /Applications/Xcode_15.0.app
    - name: Swift Lint
      run: swiftlint --strict
    - name: Test iOS
      run: xcodebuild test -scheme fs-contact-store -destination "platform=iOS Simulator,name=iPhone 15" -enableCodeCoverage YES -skipPackagePluginValidation
    - name: Fetch Coverage
      uses: sersoft-gmbh/swift-coverage-action@v4
      id: coverage-files
    - name: Publish Coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Test macOS
      run: xcodebuild test -scheme fs-contact-store -destination "platform=macOS" -enableCodeCoverage YES
  linux-unit:
    runs-on: ubuntu-latest
    container: swift:jammy
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
